openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: Telegrammo
  description: le API di Telegrammo
  version: 1.0.0
paths:
  /user:
    post:
      tags: ["login"]
      operationId: doLogin
      summary: "login"
      description: "logs in the user if it exists, otherwise creates it"
      requestBody: 
        description: "username"
        content:
          application/json: 
            schema: 
              description: "username"
              type: object
              properties:
                
                username:
                  type: string
                  minLength: 1
                  maxLength: 16
                  pattern: ^[a-zA-Z0-9]+$
                  example: "pippobaudo12"
      responses: 
        "200": 
          description: "user logged in"
          content:
            application/json:
              schema:
                description: "return id"
                type: object
                properties:
                  identifier: 
                    type: integer
                    minimum: 1
                    maximum: 10000
                    example: 124
        "400":
          $ref: "#/components/responses/Bad_Input"
        "500":
          $ref: "#/components/responses/500_ISE"
  /user/name:
    put:
      tags: ["user"]
      security:
        - bearerAuth: []
      
      operationId: setMyUserName
      summary: "modify username"
      description: "first check that the user's username is not duplicated, then change it"
      requestBody: 
        description: "take new username"
        content:
          application/json: 
            schema: 
              description: "new username"
              type: object
              properties:
                
                username:
                  type: string
                  minLength: 1
                  maxLength: 16
                  pattern: ^[a-zA-Z0-9]+$
                  example: "pippobaudo12"
      responses: 
        "200": 
          description: "username changed"
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "409":
          $ref: "#/components/responses/409_Conflict"
        "500":
          $ref: "#/components/responses/500_ISE"
  /user/photo:
    put:
      tags: ["user"]
      security:
        - bearerAuth: []
      operationId: setMyPhoto
      summary: "modify photo"
      description: "if the user has not set a photo then set it, otherwise change it"
      requestBody:
        description: "the photo is taken"
        content:
          multipart/form-data: 
            schema:
              description: "profile photo"
              type: object
              properties:
                propic: 
                  type: string
                  format: binary
      responses:
        "204": 
          $ref: "#/components/responses/204_NoContent"
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "500":
          $ref: "#/components/responses/500_ISE"
        
  /users/{id}:
    get:
      tags: ["user"]
      security:
        - bearerAuth: []
      operationId: getMyUser
      summary: "takes all the user's parameters"
      description: "takes all the user's parameters(id, username, propic)"
      parameters:
        - name: id
          in: path
          required: true
          description: "user id"
          schema:
            description: "user id"
            type: integer
            minimum: 1
            maximum: 10000
            example: 1
      responses:
        "200":
          description: "return username, propic and id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "500":
          $ref: "#/components/responses/500_ISE"

  /conversation: 
    post:
      tags: ["conversation"]
      security:
        - bearerAuth: []
      operationId: createChat
      summary: "create a chat"
      description: "if the chat already exists it does not create it, otherwise it creates it"
      requestBody:
        description: "chat data"
        content:
          multipart/form-data:
            schema:
              description: "partecipants"
              type: object
              properties:
                participants:
                  description: "array of all chat participants"
                  type: array
                  minItems: 1
                  maxItems: 10000
                  default: []
                  items: 
                    type: object
                    properties:
                      iduser: 
                        description: "user id"
                        type: integer
                        minimum: 1
                        maximum: 10000
                        example: 13
                nome:
                  description: "group name"
                  type: string
                  minLength: 1
                  maxLength: 999999
                  example: "carciofo"
                gruppo:
                  description: "False if is not a group, True if is a group"
                  type: boolean 
                  example: False
                propic:
                  description: "group profile photo"
                  type: string
                  format: binary
      responses:
        "200": 
          description: "chat create successfully"
          content:
            application/json:
              schema:
                description: "return id chat"
                type: object
                properties:
                  identifier: 
                    type: integer
                    minimum: 1
                    maximum: 10000
                    example: 124
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "409":
          $ref: "#/components/responses/409_Conflict"
        "500":
          $ref: "#/components/responses/500_ISE"

  /search/users/{username}:
    get:  
      tags: ["user"]
      security:
        - bearerAuth: []
      operationId: checknames
      summary: "takes some users"
      description: "takes all the user's parameters(id, username, propic) that username input is substring of username"
      parameters:
        - name: username
          in: path
          required: true
          description: "username to find"
          schema:
            description: "username to find"
            type: string
            minLength: 1
            pattern: ^[a-zA-Z0-9]+$
            maxLength: 16
            example: "giorgio"
      responses:
        "200":
          description: "return username, propic and id of all users who meet the requirement "
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "500":
          $ref: "#/components/responses/500_ISE"
  /search/chat/{nomeChat}:
    get:
      tags: ['conversation']
      security:
        - bearerAuth: []
      operationId: checkChatNames
      summary: "take some chats"
      description: "takes all the chat's parameters that username input is substring of chat"
      parameters:
        - name: nomeChat
          in: path
          required: true
          description: "chat to find"
          schema:
            description: "chat to find"
            type: string
            minLength: 1
            pattern: ^[a-zA-Z0-9]+$
            maxLength: 16
            example: "giorgio"
      responses:
        "200": 
          description: "return found chats"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChatUtente"
        "400":
          $ref: "#/components/responses/Bad_Input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "500":
          $ref: "#/components/responses/500_ISE"
  /conversations:
    get:
      tags: ["conversation"]
      security:
        - bearerAuth: []
      operationId: getMyConversations
      summary: "get current user chat"
      description: "get current user chats and groups after authentication "
      responses:
        "200":
          description: "return all user's chats"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChatUtente"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "500":
          $ref: "#/components/responses/500_ISE"

  /conversation/{idChat}:
    get:
      tags: ["conversation"]
      security:
        - bearerAuth: []
      operationId: getConversation
      summary: "get chat or group"
      description: "get the messages of chat or group after authentication"
      parameters:
        - name: idChat
          in: path
          required: true
          description: "chat id"
          schema:
            description: "chat id"
            type: integer
            minimum: 1
            maximum: 10000
            example: 1
      responses:
        "200":
          description: "return all chat's messages"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mess"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "500":
          $ref: "#/components/responses/500_ISE"
components:
  schemas:
    id: 
      description: "user id"
      type: integer
      minimum: 1
      maximum: 10000
      example: 1
    username:
      description: "user username"
      type: string
      minLength: 1
      maxLength: 16
      example: pippo
      pattern: ^[a-zA-Z0-9]+$
    propic:
      description: "user profile photo"
      type: string
      format: binary
    user:
      description: "type user object with username, id and propic inside"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        username:
          $ref: "#/components/schemas/username"
        propic:
          $ref: "#/components/schemas/propic"
    Group:
      type: object
      properties:
        NomeChat:
          description: "chat name"
          type: string
          maxLength: 16
          minLength: 1
          example: "pluto"
        Propric:
          description: "group propic"
          type: string
          format: byte
        Membri:
          description: "group members id"
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 10000
            example: 1
        IdChat:
          description: "chat(group) id"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
    ChatUtente:
      type: object
      properties:
        IdChat:
          description: "chat id"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        Nome:
          description: "chat name"
          type: string
          maxLength: 16
          minLength: 1
          example: "pippo"
        Gruppo:
          description: "true if the chat is a group, otherwise false"
          type: boolean
          example: true
        Username:
          description: "user username who has send the last message to the chat"
          type: string
          maxLength: 16
          minLength: 1
          example: "paolino"
        Id: 
          description: "user id who has send the last message to the chat"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        Propic:
          description: "chat profile picture"
          type: string
          format: byte
        LastMsg:
          description: "last message text"
          type: string
          maxLength: 100
          minLength: 0
          example: "ciao come ti chiami?$"
        Data:
          description: "last message date"
          type: string
          format: date-time
          example: "2021-06-01T10:00:00Z"
    Mess:
      type: object
      properties:
        IdMess:
          description: "message id"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        Nome:
          description: "sender username"
          type: string 
          minLength: 1
          maxLength: 16
          example: "pippo"
        IdMitt:
          description: "sender id"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1 
        Testo:
          description: "message text"
          type: string
          minLength: 0
          maxLength: 10000
          example: "ciao, sono pippo"
        Data:
          description: "date of message sent"
          type: string
          format: date-time
          example: "2021-06-01T10:00:00Z"
        Visual:
          description: "if the message was viewed"
          type: boolean 
          example: true
        Photo:
          description: "photo in send message"
          type: string
          format: byte
        IdChat:
          description: "chat id"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        Gruppo:
          description: "if the message belongs to a group"
          type: boolean
          example: true
        Emoji:
          description: "array of 5 elements, the number of each indicates how many emojis that message has for each type of emoji"
          type: array
          items:
            type: integer
        MyEmoji:
          description: "indicates the emoji of the user logged in to that message"
          type: string
          minLength: 1
          maxLength: 30
          example: "❤️"
        ForwardUsername:
          description: "username of the user who created the message to be forwarded"
          type: string
          minLength: 1
          maxLength: 16
          example: "pippo"
        ForwardId:
          description: "id of the user who created the message to be forwarded"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        ForwardDate:
          description: "forward date"
          type: string
          format: date-time
          example: "2021-06-01T10:00:00Z"
        ForwardIdMit: 
          description: "id of the person who made the forward"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        ForwardUsernameMit:
          description: "username of the person who made the forward"
          type: string
          minLength: 1
          maxLength: 16
          example: "pippo"
        IdForward:
          description: "id of forward"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        IdReply:
          description: "id of reply"
          type: integer
          minimum: 1
          maximum: 10000
          example: 1
        TestoReply:
          description: "text of reply message"
          type: string
          minLength: 1
          maxLength: 10000
          example: "ciao amico mio, come stai?"
        IdMitReply:
          description: "id reply sender"
          type: integer
          minimum: 1
          maximum: 1000
          example: 1
        MitReply:
          description: "username reply sender"
          type: string
          minLength: 1
          maxLength: 16
          example: "pippo"
        PhotoReply:
          description: "photo in reply message"
          type: string
          format: byte

      
  responses:
    Bad_Input:
      description: "error in log in"
      content:
        application/json:
          schema:
            description: "return an error"
            type: object
            properties:
              error: 
                type: string
                minLength: 1
                maxLength: 1000
                example: "error in data structure"
    204_NoContent:
      description: No content, operation successful

    401_Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            description: Unauthorized response
            type: object
            properties:
              message:
                description: Unauthorized message
                type: string
                example: "Unauthorized"
                minLength: 0
                maxLength: 10000
                pattern: "^.*?$"

    403_Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            description: Forbidden response
            type: object
            properties:
              message:
                description: Forbidden message
                type: string
                example: "Forbidden"
                minLength: 0
                maxLength: 10000
                pattern: "^.*?$"

    404_NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            description: Not Found response
            type: object
            properties:
              message:
                description: Not Found message
                type: string
                example: "Not Found"
                minLength: 0
                maxLength: 10000
                pattern: "^.*?$"

    409_Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            description: Conflict response
            type: object
            properties:
              message:
                description: Conflict
                type: string
                example: "Conflict"
                minLength: 0
                maxLength: 10000
                pattern: "^.*?$" 
    500_ISE:
      description: internal server error
      content:
        application/json:
          schema:
            description: internal server error response
            type: object
            properties:
              message:
                description: internal server error
                type: string
                example: "internal server error"
                minLength: 0
                maxLength: 10000
                pattern: "^.*?$" 
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header
      name: cs