openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: Telegrammo
  description: le API di Telegrammo
  version: 1.0.0
paths:
  /user:
    post:
      tags: ["login"]
      operationId: doLogin
      summary: "login"
      description: "logs in the user if it exists, otherwise creates it"
      requestBody: 
        description: "username"
        content:
          application/json: 
            schema: 
              description: "username"
              type: object
              properties:
                
                username:
                  type: string
                  minLength: 1
                  maxLength: 16
                  pattern: ^[a-zA-Z0-9]+$
                  example: "pippobaudo12"
      responses: 
        "200": 
          description: "utente loggato"
          content:
            application/json:
              schema:
                description: "restituisce id"
                type: object
                properties:
                  identifier: 
                    type: integer
                    minimum: 1
                    maximum: 99999999
                    example: 124
        "400":
          $ref: "#/components/responses/bad_input"
        "500":
          description: "internal server error"
  /user/name:
    put:
      tags: ["user"]
      security:
        - bearerAuth: []
      
      operationId: setMyUserName
      summary: "modify username"
      description: "first check that the user's username is not duplicated, then change it"
      requestBody: 
        description: "take new username"
        content:
          application/json: 
            schema: 
              description: "new username"
              type: object
              properties:
                
                username:
                  type: string
                  minLength: 1
                  maxLength: 16
                  pattern: ^[a-zA-Z0-9]+$
                  example: "pippobaudo12"
      responses: 
        "200": 
          description: "username changed"
        "400":
          $ref: "#/components/responses/bad_input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "409":
          $ref: "#/components/responses/409_conflict"
        "500":
          $ref: "#/components/responses/500_ISE"
  /user/photo:
    put:
      tags: ["user"]
      security:
        - bearAuth: []
      operationId: setMyPhoto
      summary: "modifica photo"
      description: "se l'utente non ha impostata una foto allora la imposta, altrimenti la cambia"
      requestBody:
        description: "viene presa la foto"
        content:
          multipart/form-data: 
            schema:
              description: "foto profilo"
              type: object
              properties:
                propic: 
                  type: string
                  format: binary
      responses:
        "204": 
          description: "foto cambiata"
        "400":
          $ref: "#/components/responses/bad_input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "500":
          $ref: "#/components/responses/500_ISE"
        
  /users/{id}:
    get:
      tags: ["user"]
      security:
        - bearerAuth: []
      operationId: getUser
      summary: "takes all the user's parameters"
      description: "takes all the user's parameters(id, username, propic)"
      parameters:
        - name: id
          in: path
          required: true
          description: "user id"
          schema:
            description: "user id"
            type: integer
            minimum: 1
            maximum: 99999999
            example: 1
      responses:
        "200":
          description: "return username, propic and id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          $ref: "#/components/responses/bad_input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "400":
          $ref: "#/components/responses/bad_input"
        "500":
          $ref: "#/components/responses/500_ISE"

  /conversation: 
    post:
      tags: ["conversation"]
      operationId: createChat
      summary: "crea una chat"
      description: "se la chat gia' esiste non la crea, se non esiste la crea"
      requestBody:
        description: "dati chat"
        content:
          multipart/form-data:
            schema:
              description: "partecipanti"
              type: object
              properties:
                participants:
                  description: "array di tutti i partecipanti alla chat"
                  type: array
                  minItems: 1
                  maxItems: 999999
                  default: []
                  items: 
                    type: object
                    properties:
                      iduser: 
                        description: "id dello user"
                        type: integer
                        minimum: 1
                        maximum: 999999
                        example: 13
                nome:
                  description: "nome del gruppo"
                  type: string
                  minLength: 1
                  maxLength: 999999
                  example: "carciofo"
                gruppo:
                  description: "False if is not a group, True if is a group"
                  type: boolean 
                  example: False
                propic:
                  description: "group propic"
                  type: string
                  format: binary
      responses:
        "200": 
          description: "chat create successfully"
          content:
            application/json:
              schema:
                description: "return id"
                type: object
                properties:
                  identifier: 
                    type: integer
                    minimum: 1
                    maximum: 99999999
                    example: 124
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "409":
          $ref: "#/components/responses/409_conflict"
        "500":
          $ref: "#/components/responses/500_ISE"

  /search/users/{username}:
    get:  
      tags: ["user"]
      security:
        - bearerAuth: []
      operationId: getUser
      summary: "takes some users"
      description: "takes all the user's parameters(id, username, propic) that username input is substring of username"
      parameters:
        - name: username
          in: path
          required: true
          description: "username to find"
          schema:
            description: "username to find"
            type: string
            minlength: 1
            pattern: ^[a-zA-Z0-9]+$
            maxlength: 99999999
            example: "giorgio"
      responses:
        "200":
          description: "return username, propic and id of all users who meet the requirement "
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        "400":
          $ref: "#/components/responses/bad_input"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "500":
          $ref: "#/components/responses/500_ISE"

  /conversations:
    get:
      tags: ["conversation"]
      security:
        - bearerAuth: []
      operationId: getMyConversations
      summary: "get current user chat"
      description: "get current user chats and groups after authentication "
      responses:
        "200":
          description: "return all user's chats"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IdChat:
                      description: "chat or group id"
                      type: integer
                      minimum: 1
                      maximum: 99999999
                      example: 124
                    Nome:
                      description: "chat or group name"
                      type: string
                      minLength: 1
                      maxLength: 999999
                      example: "carciofo"
                    Gruppo:
                      description: "True if is a group, False if is not a group"
                      type: boolean
                      example: False
                    Username:
                      description: "username of the other user"
                      type: string
                      minLength: 1
                      maxLength: 16
                      example: "pippobaudo12"
                    Id:
                      description: "id of the other user if is not a group"
                      type: integer
                      minimum: 1
                      maximum: 99999999
                      example: 124
                    Propic:
                      description: "propic of the other user or group"
                      type: string
                      format: binary
                    LastMsg:
                      description: "text of the last message of this chat"
                      type: string
                      minLength: 1
                      maxLength: 999999
                      example: "ciao"
                    Data:
                      description: "date of the last message of this chat"
                      type: string
                      format: date-time
                      example: "2021-06-01T10:00:00Z"

        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "500":
          $ref: "#/components/responses/500_ISE"

  /conversation/{idChat}:
    get:
      tags: ["conversation"]
      security:
        - bearerAuth: []
      operationId: getConversation
      summary: "get chat or group"
      description: "get the messages of chat or group after authentication"
      parameters:
        - name: idChat
          in: path
          required: true
          description: "chat id"
          schema:
            description: "chat id"
            type: integer
            minimum: 1
            maximum: 99999999
            example: 1
      responses:
        "200":
          description: "return all chat's messages"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IdMess:
                      description: "message id"
                      type: integer
                      minimum: 1
                      maximum: 99999999
                      example: 124
                    Nome:
                      description: "user id"
                      type: integer
                      minimum: 1
                      maximum: 99999999
                      example: 124
                    Username:
                      description: "username of the user"
                      type: string
                      minLength: 1
                      maxLength: 16
                      example: "pippobaudo12"
                    Propic:
                      description: "propic of the user"
                      type: string
                      format: binary
                    Text:
                      description: "text of the message"
                      type: string
                      minLength: 1
                      maxLength: 999999
                      example: "ciao"
                    Data:
                      description: "date of the message"
                      type: string
                      format: date-time
                      example: "2021-06-01T10:00:00Z"
        "401":
          $ref: "#/components/responses/401_Unauthorized"
        "404":
          $ref: "#/components/responses/404_NotFound"
        "500":
          $ref: "#/components/responses/500_ISE"
components:
  schemas:
    id: 
      description: "user id"
      type: integer
      minimum: 1
      maximum: 99999999
      example: 1
    username:
      description: "user username"
      type: string
      minLenght: 1
      maxLenght: 16
      example: pippo
      pattern: ^[a-zA-Z0-9]+$
    propic:
      description: "user profile photo"
      type: string
      format: binary
    user:
      description: "type user object with username, id and propic inside"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        username:
          $ref: "#/components/schemas/username"
        propic:
          $ref: "#/components/schemas/propic"
  responses:
    bad_input:
      description: "error in log in"
      content:
        application/json:
          schema:
            description: "return an error"
            type: object
            properties:
              error: 
                type: string
                minLength: 1
                maxLength: 1000
                example: "error in data structure"
    204_NoContent:
    description: No content, operation successful

    401_Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            description: Unauthorized response
            type: object
            properties:
              message:
                description: Unauthorized message
                type: string
                example: "Unauthorized"
                minLength: 0
                maxLength: 999999999
                pattern: "^.*?$"

    403_Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            description: Forbidden response
            type: object
            properties:
              message:
                description: Forbidden message
                type: string
                example: "Forbidden"
                minLength: 0
                maxLength: 999999999
                pattern: "^.*?$"

    404_NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            description: Not Found response
            type: object
            properties:
              message:
                description: Not Found message
                type: string
                example: "Not Found"
                minLength: 0
                maxLength: 999999999
                pattern: "^.*?$"

    409_Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            description: Conflict response
            type: object
            properties:
              message:
                description: Conflict
                type: string
                example: "Conflict"
                minLength: 0
                maxLength: 999999999
                pattern: "^.*?$" 
    500_ISE:
      description: internal server error
      content:
        application/json:
          schema:
            description: internal server error response
            type: object
            properties:
              message:
                description: internal server error
                type: string
                example: "internal server error"
                minlength: 0
                maxlength: 999999999
                pattern: "^.*?$" 
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header
      name: cs